apiVersion: example.com/v1
kind: Microservice
metadata:
  name: sample-microservice-1
spec:
  applicationName: "sample-app"
  parameters:
    - name: "param1"
      value: "some-value"
    - name: "param2"
      value: "another-value"

---

apiVersion: example.com/v1
kind: Microservice
metadata:
  name: sample-microservice-2
spec:
  applicationName: "sample-app"
  parameters:
    - name: "param1"
      value: "another-value"
    - name: "param2"
      value: "yet-another-value"