apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: microservices.example.com
spec:
  group: example.com
  names:
    kind: Microservice
    listKind: MicroserviceList
    plural: microservices
    singular: microservice
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            applicationName:
              type: string
              description: "The name of the microservice application"
            parameters:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    description: "The name of the parameter"
                  value:
                    type: string
                    description: "The value of the parameter"