apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ipcameras.devices.example.com
spec:
  group: devices.example.com
  names:
    kind: IPCamera
    listKind: IPCameraList
    plural: ipcameras
    singular: ipcamera
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deviceId:
                  type: string
                name:
                  type: string
                ipAddress:
                  type: string
                location:
                  type: string
                settings:
                  type: object
                  properties:
                    resolution:
                      type: string
                    frameRate:
                      type: string
                status:
                  type: string
                rtspUrl:
                  type: string
                streamSettings:
                  type: object
                  properties:
                    codec:
                      type: string
                    audioEnabled:
                      type: boolean
              required:
                - deviceId
                - name
                - ipAddress
                - status
                - rtspUrl
                - streamSettings
  subresources:
    status: {}